# File .chipperci.yml, which goes in the root of your repository
version: 1
environment:
  php: 8.1    # 7.1, 7.2, 7.3, 7.4, 8.0, 8.1
  node: 16    # 6, 8, 10, 12, 14, 16
#services:
#  - mysql: 5.7
pipeline:
  - name: Setup
    cmd: |
      cp -v .env.example .env
      composer install --no-interaction --prefer-dist --optimize-autoloader
      php artisan key:generate
  - name: Deploy Vapor
    cmd: |
      if [[ $CI_COMMIT_BRANCH == 'staging' ]]; then
        vendor/bin/vapor deploy staging --commit="${CI_COMMIT_SHA}" --message="${CI_COMMIT_MESSAGE}"
      fi
      if [[ $CI_COMMIT_BRANCH == 'main' ]]; then
        vendor/bin/vapor deploy production --commit="${CI_COMMIT_SHA}" --message="${CI_COMMIT_MESSAGE}"
      fi
